{% set name = "Lasagne" %}
{% set version = "0.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '3c634ecab67e43e4f18520932bfd88bd3c678ec723c48177f18799dab2411233'

build:
  number: 2
  skip: true  # [win or py>36]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - numpy
    - theano ==0.8.2

test:
  imports:
    - lasagne
    - lasagne.layers
    - lasagne.theano_extensions

about:
  home: https://github.com/Lasagne/Lasagne
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A lightweight library to build and train neural networks in Theano
  description: A lightweight library to build and train neural networks in Theano
  dev_url: https://github.com/Lasagne/Lasagne

extra:
  recipe-maintainers:
    - nick-youngblut
