travis:
  secure:
    BINSTAR_TOKEN: kSy+JNJMs7L2NVIm+9XrG5Ju2R4wYk70Q762NT5cDLGjw+l+mGhuYr5mw4hUJPn++OWecvPHfzg4ektDL3AfbvORqyqaHkpbVX8zYRng7SSDqFvAW1Umr5BjC2iPTSsaARvQcPFOdSluVJXO3ygmn8NHLv1LaHLvX0MMctBHgxUcYm97T+R9SXPPQyzx3lAj//odMxGjGVFTv2cGkTobI/DsRsRiZCQGXVu59flaAWORamg/TECvgl4kItJ85Bv8zKhkBV9MapgIphatU6HYJmce8LAGOdl208rFPA21UdKT0hs89MEKYzdOE1Zt3lpVjOdlRilHRq62CnI9b9qLsLolBnYAIw4xXlbgTNSuIh5YjRe+tziKYFcSthugsZ5hMORUDY7RMeMvqVJ9MEmzrRVPNKTdG4W9ZT1fCGzKAHIWgb6737j+eSLwEfjzsF34PHPYjSr4nGRrX9TTtrQzQehlGBq7GnoOXB4knaWLPmWh0WfKiREN3vf7MizPzH2N171wLeltbhFcv48seNfVqNogWkRW9ApZhmIcybaKK5YCXFAT76uRLqZhi09YGp6h3DPPzdZXcQt9EhvVJfJv54+JIVbdQDnh3McCZkwqFOw9QAqfXDK7cM0LNXQH2gN/G8ByTWnJ56IQBLRwIT+OMZzUCREknIL/rBofK/UMl9I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
